apiVersion: v1
kind: ConfigMap
metadata:
  name: rus
  namespace: default
  labels:
    ran-placer: "rus"
data:
  rus: |
    {
        "node0": {
            "RU": 0
        },
        "node1": {
            "RU": 1
        },
        "node2": {
            "RU": 1
        },
        "node3": {
            "RU": 1
        },
        "node4": {
            "RU": 1
        }
    }
