apiVersion: v1
kind: Service
metadata:
  name: algorithm-scheduler
  namespace: default
  labels:
    app: algorithm-scheduler
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
  selector:
    app: algorithm-scheduler
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: algorithm-scheduler
  namespace: default
  labels:
    app: algorithm-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: algorithm-scheduler
  template:
    metadata:
      labels:
        app: algorithm-scheduler
    spec:
      containers:
        - name: algorithm-scheduler
          imagePullPolicy: Always
          image: 10.43.0.201:5000/algorithm-scheduler:1
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          env:
            - name: "DOCKER_REPOSITORY"
              value: "10.43.0.201:5000"
