FROM oaisim_base

RUN cd openairinterface5g && git checkout -f 2020.w30

COPY user_api.c /openairinterface5g/openair3/NAS/UE/API/USER/user_api.c
RUN cd openairinterface5g/cmake_targets && sudo ./build_oai --UE -I -c
