  
FROM ubuntu:18.04

#ENV DEBIAN_FRONTEND=noninteractive
ENTRYPOINT ["tail", "-f", "/dev/null"]

#RUN apt-get update

#RUN apt-get install -y git vim nano net-tools \
#    cmake g++ kmod linux-image-$(uname -r) linux-headers-$(uname -r) \
#    sudo iputils-ping curl unzip dumb-init

#RUN adduser l2nfapi
#RUN adduser l2nfapi sudo
#RUN echo "l2nfapi      ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

#USER l2nfapi
#USER root

#RUN DEBIAN_FRONTEND=noninteractive apt install -y tzdata

#RUN git clone https://gitlab.eurecom.fr/oai/openairinterface5g.git