apiVersion: v1
kind: ConfigMap
metadata:
  name: topology
  namespace: default
  labels:
    ran-placer: "topology"
data:
  topology: |
    {
        "node16--node-3": {
            "linkNumber": "1",
            "fromNode": "0",
            "toNode": "1",
            "delay": "0.163",
            "capacity": "10000"
        }
    }
